<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate Compliment</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap');

        body {
            font-family: 'Poppins', sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #f6d365 0%, #fda085 100%);
            background-size: 200% 200%;
            animation: gradientShift 20s ease infinite;
            color: #333;
            overflow: hidden;
            position: relative;
        }

        @keyframes gradientShift {
            0% { background-position: 0% 0%; }
            50% { background-position: 100% 100%; }
            100% { background-position: 0% 0%; }
        }

        #compliment-button {
            background-color: #fff;
            border: none;
            color: #333;
            padding: 16px 32px;
            font-size: 18px;
            cursor: pointer;
            border-radius: 30px;
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease, box-shadow 0.3s ease, background-color 0.3s ease, filter 0.3s ease;
            outline: none;
            position: relative;
            overflow: hidden;
        }

        #compliment-button:hover {
            background-color: #fdfdfd;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            transform: scale(1.05);
        }

        #compliment-button:active::before {
            content: '';
            position: absolute;
            top: 50%;
            left: 50%;
            width: 200%;
            padding-bottom: 200%;
            background-color: rgba(255, 255, 255, 0.4);
            transform: translate(-50%, -50%);
            border-radius: 50%;
            animation: ripple 0.8s ease;
        }

        @keyframes ripple {
            to {
                width: 300%;
                padding-bottom: 300%;
                opacity: 0;
            }
        }

        #compliment {
            margin-top: 30px;
            font-size: 26px;
            text-align: center;
            max-width: 80%;
            word-wrap: break-word;
            padding: 20px;
            background-color: rgba(255, 255, 255, 0.9);
            border-radius: 20px;
            box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
            opacity: 0;
            transform: scale(0.9) translateY(20px);
            transition: all 0.8s ease;
            font-weight: 300;
            letter-spacing: 0.5px;
            position: relative;
            overflow: hidden;
        }

        #compliment.show {
            opacity: 1;
            transform: scale(1) translateY(0);
        }

        /* Subtle Text Animation */
        .text-glow {
            position: relative;
            display: inline-block;
            font-size: 26px;
            color: #aa336a;
            background: linear-gradient(90deg, #ff9a9e, #f6d365, #fda085);
            background-clip: text;
            -webkit-background-clip: text;
            animation: textGlow 5s ease-in-out infinite, textPulse 1.5s ease-in-out infinite;
            text-shadow: 0 0 15px rgba(255, 105, 180, 0.8), 0 0 30px rgba(255, 105, 180, 0.6);
        }

        @keyframes textGlow {
            0%, 100% {
                text-shadow: 0 0 10px rgba(255, 105, 180, 0.6), 0 0 20px rgba(255, 105, 180, 0.6);
            }
            50% {
                text-shadow: 0 0 30px rgba(255, 105, 180, 1), 0 0 40px rgba(255, 105, 180, 1);
            }
        }

        @keyframes textPulse {
            0%, 100% {
                transform: scale(1);
            }
            50% {
                transform: scale(1.05);
            }
        }

        /* Floating Particles */
        .particle {
            position: absolute;
            width: 12px;
            height: 12px;
            background-color: rgba(255, 182, 193, 0.7);
            border-radius: 50%;
            animation: float 8s ease-in-out infinite;
            opacity: 0.6;
        }

        @keyframes float {
            0% { transform: translateY(0); opacity: 0.6; }
            50% { opacity: 1; }
            100% { transform: translateY(-100vh); opacity: 0; }
        }

        /* Subtle Background Effects */
        .background-shape {
            position: absolute;
            border-radius: 50%;
            background-color: rgba(255, 182, 193, 0.4);
            pointer-events: none;
            mix-blend-mode: soft-light;
        }

        .shape-1 {
            width: 100px;
            height: 100px;
            top: 20%;
            left: 10%;
            animation: move1 15s linear infinite;
        }

        .shape-2 {
            width: 120px;
            height: 120px;
            top: 50%;
            left: 40%;
            animation: move2 20s linear infinite;
        }

        .shape-3 {
            width: 140px;
            height: 140px;
            top: 70%;
            left: 60%;
            animation: move3 25s linear infinite;
        }

        @keyframes move1 {
            0% { transform: translate(0, 0); }
            100% { transform: translate(250px, -250px); }
        }

        @keyframes move2 {
            0% { transform: translate(0, 0); }
            100% { transform: translate(-200px, 200px); }
        }

        @keyframes move3 {
            0% { transform: translate(0, 0); }
            100% { transform: translate(300px, -300px); }
        }

    </style>
</head>
<body>

    <div>
        <button id="compliment-button">Generate Compliment</button>
        <p id="compliment"></p>
    </div>

    <script>
        const compliments = [
            "You're surprisingly not as terrible as I expected!",
            "I guess even a broken clock is right twice a day.",
            "You know, for someone who tries so hard, you don't do too badly.",
            "It's amazing how you manage to be so average.",
            "You're like a cloud. When you disappear, it's a beautiful day.",
            "It's impressive how you can be both brilliant and dull at the same time.",
            "You have a unique way of making things seem more complicated than they are.",
            "Your ability to blend into the background is unmatched.",
            "You're not completely useless; you can always serve as a bad example.",
            "It's cute how you think you're making a difference.",
            "You’re like a car crash—hard to look away from, but you’re glad when it’s over.",
            "You really do have a talent for lowering expectations."
        ];

        const button = document.getElementById('compliment-button');
        const complimentText = document.getElementById('compliment');
        const particlesContainer = document.createElement('div');
        particlesContainer.style.position = 'absolute';
        particlesContainer.style.top = 0;
        particlesContainer.style.left = 0;
        particlesContainer.style.width = '100%';
        particlesContainer.style.height = '100%';
        particlesContainer.style.pointerEvents = 'none';
        document.body.appendChild(particlesContainer);

        function createParticle(x, y) {
            const particle = document.createElement('div');
            particle.classList.add('particle');
            particle.style.left = x + 'px';
            particle.style.top = y + 'px';
            particle.style.width = Math.random() * 14 + 'px';
            particle.style.height = particle.style.width;
            particle.style.animationDuration = Math.random() * 4 + 4 + 's';
            particlesContainer.appendChild(particle);
            setTimeout(() => particle.remove(), 6000);
        }

        button.addEventListener('click', () => {
            const randomCompliment = compliments[Math.floor(Math.random() * compliments.length)];
            complimentText.textContent = ''; // Clear previous compliment text

            complimentText.classList.remove('show');

            // Create glowing text animation with scaling pulse
            setTimeout(() => {
                complimentText.innerHTML = `<span class="text-glow">${randomCompliment}</span>`;
                complimentText.classList.add('show');
            }, 100);

            // Generate floating particles at random positions
            for (let i = 0; i < 20; i++) {
                createParticle(Math.random() * window.innerWidth, Math.random() * window.innerHeight);
            }
        });

        // Handle particles following the cursor
        document.addEventListener('mousemove', (e) => {
            createParticle(e.clientX, e.clientY);
        });

        // Create subtle background shapes
        function createBackgroundShape() {
            const shapes = ['shape-1', 'shape-2', 'shape-3'];
            const shape = document.createElement('div');
            shape.classList.add('background-shape', shapes[Math.floor(Math.random() * shapes.length)]);
            document.body.appendChild(shape);
            setTimeout(() => shape.remove(), 20000);
        }

        // Continuously create background shapes
        setInterval(createBackgroundShape, 5000);
    </script>

</body>
</html>
